=== Engin1980/ChlaotSolution/ChecklistModule/Xmls/ChecklistSchema.xsd
<?xml version="1.0" encoding="utf-8"?>
<xsd:schema id="Schema"
            targetNamespace="http://tempuri.org/Schema.xsd"
            elementFormDefault="qualified"
            xmlns="http://tempuri.org/Schema.xsd"
            xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <xsd:element name="checklistSet">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="meta" minOccurs="1" maxOccurs="1" type="metadata"/>
        <xsd:element name="checklist" minOccurs="1" maxOccurs="unbounded" type="checklist"/>
      </xsd:sequence>
      <xsd:attribute name="firstChecklistId" type="nonemptyString" use="required" />
    </xsd:complexType>
  </xsd:element>

  <xsd:complexType name="metadata">
    <xsd:choice maxOccurs="unbounded">
      <xsd:element name="author" minOccurs="1" maxOccurs="1" type="nonemptyString"/>
      <xsd:element name="label" minOccurs="1" maxOccurs="1" type="nonemptyString"/>
      <xsd:element name="description" minOccurs="1" maxOccurs="1" type="xsd:string"/>
      <xsd:element name="web" minOccurs="0" maxOccurs="1" type="xsd:string"/>
      <xsd:element name="email" minOccurs="0" maxOccurs="1" type="xsd:string"/>
      <xsd:element name="license" minOccurs="0" maxOccurs="1" type="xsd:string"/>
    </xsd:choice>
  </xsd:complexType>

  <xsd:complexType name="checklist">
    <xsd:sequence>
      <xsd:element name="item" minOccurs="1" maxOccurs="unbounded" type="item"/>
      <xsd:element name="metaInfo" minOccurs="0" maxOccurs="1" type="checklistMetaInfo" />
      <xsd:element name="nextChecklistId" minOccurs="1" maxOccurs="1" type="nextChecklistId" />
    </xsd:sequence>
    <xsd:attribute name="id" type="nonemptyString" use="required"/>
    <xsd:attribute name="callSpeech" type="nonemptyString" use="optional"/>
    <xsd:attribute name="sequence" type="xsd:integer" use="optional"/>
    <xsd:attribute name="beginCallFile" type="nonemptyString" use="optional"/>
    <xsd:attribute name="endCallFile" type="nonemptyString" use="optional"/>
  </xsd:complexType>

  <xsd:complexType name="checklistMetaInfo">
    <xsd:sequence>
      <xsd:element name="autostart" minOccurs="0" maxOccurs="1" type="autostartConditionTop" />
      <xsd:element name="customEntrySpeech" minOccurs="0" maxOccurs="1" type="callOrConfirmation" />
      <xsd:element name="customExitSpeech" minOccurs="0" maxOccurs="1" type="callOrConfirmation" />
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="autostartConditionTop">
    <xsd:choice minOccurs="1" maxOccurs="1">
      <xsd:element name="and" type="autostartCondition"/>
      <xsd:element name="or" type="autostartCondition"/>
      <xsd:element name="property" type="autostartProperty"/>
      <xsd:element name="for" type="autostartDelay" />
    </xsd:choice>
  </xsd:complexType>

  <xsd:complexType name="autostartCondition">
    <xsd:choice minOccurs="1" maxOccurs="unbounded">
      <xsd:element name="and" type="autostartCondition"/>
      <xsd:element name="or" type="autostartCondition"/>
      <xsd:element name="property" type="autostartProperty"/>
      <xsd:element name="for" type="autostartDelay" />
    </xsd:choice>
  </xsd:complexType>

  <xsd:complexType name="autostartDelay">
    <xsd:choice minOccurs="1" maxOccurs="1">
      <xsd:element name="and" type="autostartCondition"/>
      <xsd:element name="or" type="autostartCondition"/>
      <xsd:element name="property" type="autostartProperty"/>
    </xsd:choice>
    <xsd:attribute name="seconds" type="xsd:nonNegativeInteger" use="required" />
  </xsd:complexType>

  <xsd:complexType name="autostartProperty">
    <xsd:attribute name="name" type="autostartPropertyName" use="required"/>
    <xsd:attribute name="direction" type="autostartPropertyDirection" use="required" />
    <xsd:attribute name="value" type="xsd:integer" use="required"/>
    <xsd:attribute name="nameIndex" type="xsd:integer" use="optional" />
  </xsd:complexType>

  <xsd:simpleType name="autostartPropertyDirection">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="above"/>
      <xsd:enumeration value="below"/>
    </xsd:restriction>
  </xsd:simpleType>
  
  <xsd:simpleType name="autostartPropertyName">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="altitude"/>
      <xsd:enumeration value="height"/>
      <xsd:enumeration value="gs"/>
      <xsd:enumeration value="ias" />
      <xsd:enumeration value="bank" />
      <xsd:enumeration value="parkingBrakeSet" />
      <xsd:enumeration value="pushbackTugConnected" />
      <xsd:enumeration value="engineStarted" />
      <xsd:enumeration value="verticalSpeed" />
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:simpleType name="autostartPropertyValue">
    <xsd:restriction base="xsd:string">
      <xsd:pattern value="((gt)|(lt))?-?\d+"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:complexType name="nextChecklistId">
    <xsd:attribute name="id" type="nonemptyString" use="optional"/>
  </xsd:complexType>

  <xsd:complexType name="item">
    <xsd:sequence>
      <xsd:element name="call" type="callOrConfirmation"/>
      <xsd:element name="confirmation" type="callOrConfirmation"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="callOrConfirmation">
    <xsd:attribute name="type" type="callOrConfirmationType" use="required"/>
    <xsd:attribute name="value" type="nonemptyString" use="required"/>
  </xsd:complexType>

  <xsd:simpleType name="callOrConfirmationType">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="file"/>
      <xsd:enumeration value="speech"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:simpleType name="nonemptyString">
    <xsd:restriction base="xsd:string">
      <xsd:pattern value=".+"/>
    </xsd:restriction>
  </xsd:simpleType>
</xsd:schema>

=== Engin1980/ChlaotSolution/ChecklistModule/Xmls/a320.xml
<?xml version="1.0" encoding="utf-8" ?>
<checklistSet
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns="http://tempuri.org/Schema.xsd"
  xsi:noNamespaceSchemaLocation="ChecklistSchema.xsd"
  firstChecklistId="batteryOn">
  <meta>
    <label>A320 FBW checklist</label>
    <author>Marek Vajgl</author>
    <description>Simple checklists test for A320 FBW customized</description>
  </meta>
  <checklist id="beforeStart" callSpeech="Before Start-up">
    <item>
      <call type="speech" value="Parking Brake"/>
      <confirmation type="speech" value="Set"/>
    </item>
    <item>
      <call type="speech" value="Seatbelts"/>
      <confirmation type="speech" value="On"/>
    </item>
    <item>
      <call type="speech" value="IRS alging"/>
      <confirmation type="speech" value="Set"/>
    </item>
    <item>
      <call type="speech" value="M C D U departure"/>
      <confirmation type="speech" value="Set"/>
    </item>
    <item>
      <call type="speech" value="Squawk Code"/>
      <confirmation type="speech" value="Set"/>
    </item>
    <item>
      <call type="speech" value="A P U"/>
      <confirmation type="speech" value="Started"/>
    </item>
    <item>
      <call type="speech" value="External Power"/>
      <confirmation type="speech" value="Disconnected"/>
    </item>
    <item>
      <call type="speech" value="Packs"/>
      <confirmation type="speech" value="Off"/>
    </item>
    <item>
      <call type="speech" value="Doors"/>
      <confirmation type="speech" value="Closed"/>
    </item>
    <item>
      <call type="speech" value="Packs"/>
      <confirmation type="speech" value="Off"/>
    </item>
    <item>
      <call type="speech" value="Throttles"/>
      <confirmation type="speech" value="Idle"/>
    </item>
    <item>
      <call type="speech" value="Surfaces"/>
      <confirmation type="speech" value="Checked"/>
    </item>
    <nextChecklistId />
  </checklist>
  <checklist id="inTaxi" callSpeech="In Taxi">
    <item>
      <call type="speech" value="Packs"/>
      <confirmation type="speech" value="On"/>
    </item>
    <item>
      <call type="speech" value="A P U Bleed"/>
      <confirmation type="speech" value="Off"/>
    </item>
    <item>
      <call type="speech" value="Flaps"/>
      <confirmation type="speech" value="Set"/>
    </item>
    <item>
      <call type="speech" value="Autobrake"/>
      <confirmation type="speech" value="Set"/>
    </item>
    <item>
      <call type="speech" value="T O check button"/>
      <confirmation type="speech" value="Green"/>
    </item>
    <item>
      <call type="speech" value="Weather Radar"/>
      <confirmation type="speech" value="On"/>
    </item>
    <nextChecklistId />
  </checklist>
  <checklist id="beforeTakeoff" callSpeech="Before Take Off">
    <item>
      <call type="speech" value="Landing Lights"/>
      <confirmation type="speech" value="On"/>
    </item>
    <item>
      <call type="speech" value="Strobe Light"/>
      <confirmation type="speech" value="On"/>
    </item>
    <item>
      <call type="speech" value="Crew"/>
      <confirmation type="speech" value="Alerted"/>
    </item>
    <item>
      <call type="speech" value="Packs"/>
      <confirmation type="speech" value="Off"/>
    </item>
    <item>
      <call type="speech" value="Squawk Mode"/>
      <confirmation type="speech" value="Charlie"/>
    </item>
    <item>
      <call type="speech" value="Terrain"/>
      <confirmation type="speech" value="As required"/>
    </item>
    <item>
      <call type="speech" value="Clock"/>
      <confirmation type="speech" value="Run"/>
    </item>
    <item>
      <call type="speech" value="Flight Director"/>
      <confirmation type="speech" value="On"/>
    </item>
    <nextChecklistId/>
  </checklist>
  <checklist id="afterTakeoff" callSpeech="After Take Off">
    <item>
      <call type="speech" value="Gear" />
      <confirmation type="speech" value="Up" />
    </item>
    <item>
      <call type="speech" value="Flaps" />
      <confirmation type="speech" value="One" />
    </item>
    <item>
      <call type="speech" value="Autopilot" />
      <confirmation type="speech" value="As required" />
    </item>
    <metaInfo>
      <autostart>
        <property name="height" direction="above" value="400"/>
      </autostart>
    </metaInfo>
    <nextChecklistId/>
  </checklist>
  <checklist id="departure" callSpeech="Departure">
    <item>
      <call type="speech" value="Flaps" />
      <confirmation type="speech" value="Up" />
    </item>
    <item>
      <call type="speech" value="A P U" />
      <confirmation type="speech" value="Off" />
    </item>
    <item>
      <call type="speech" value="Packs" />
      <confirmation type="speech" value="On" />
    </item>
    <nextChecklistId/>
  </checklist>
  <checklist id="descent" callSpeech="Descent">
    <item>
      <call type="speech" value="Pressurezation" />
      <confirmation type="speech" value="Verify" />
    </item>
    <nextChecklistId/>
  </checklist>
  <checklist id="approach" callSpeech="Approach">
    <item>
      <call type="speech" value="Landing Data" />
      <confirmation type="speech" value="Check" />
    </item>
    <nextChecklistId/>
  </checklist>
  <checklist id="beforeLanding" callSpeech="Before Landing">
    <item>
      <call type="speech" value="Landing Gear" />
      <confirmation type="speech" value="Down Three Green" />
    </item>
    <nextChecklistId id="vacated" />
    <checklist id="goAround" callSpeech="Go Around">
      <item>
        <call type="speech" value="Gear"/>
        <confirmation type="speech" value="Up"/>
      </item>
      <item>
        <call type="speech" value="Flaps"/>
        <confirmation type="speech" value="As required"/>
      </item>
      <nextChecklistId id="approach" />
    </checklist>
  </checklist>
  <checklist id="vacated" callSpeech="Vacated">
    <item>
      <call type="speech" value="Speed Brakes" />
      <confirmation type="speech" value="Retracted" />
    </item>
    <nextChecklistId id="beforeStart" />
  </checklist>
</checklistSet>
