=== Engin1980/ChlaotSolution/ChecklistModule/Xmls/ChecklistSchema.xsd
<?xml version="1.0" encoding="utf-8"?>
<xsd:schema id="Schema"
            targetNamespace="http://tempuri.org/Schema.xsd"
            elementFormDefault="qualified"
            xmlns="http://tempuri.org/Schema.xsd"
            xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <xsd:element name="checklistSet">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="meta" minOccurs="1" maxOccurs="1" type="metadata"/>
        <xsd:element name="checklist" minOccurs="1" maxOccurs="unbounded" type="checklist"/>
      </xsd:sequence>
      <xsd:attribute name="firstChecklistId" type="nonemptyString" use="required" />
    </xsd:complexType>
  </xsd:element>

  <xsd:complexType name="metadata">
    <xsd:choice maxOccurs="unbounded">
      <xsd:element name="author" minOccurs="1" maxOccurs="1" type="nonemptyString"/>
      <xsd:element name="label" minOccurs="1" maxOccurs="1" type="nonemptyString"/>
      <xsd:element name="description" minOccurs="1" maxOccurs="1" type="xsd:string"/>
      <xsd:element name="web" minOccurs="0" maxOccurs="1" type="xsd:string"/>
      <xsd:element name="email" minOccurs="0" maxOccurs="1" type="xsd:string"/>
      <xsd:element name="license" minOccurs="0" maxOccurs="1" type="xsd:string"/>
    </xsd:choice>
  </xsd:complexType>

  <xsd:complexType name="checklist">
    <xsd:sequence>
      <xsd:element name="item" minOccurs="1" maxOccurs="unbounded" type="item"/>
      <xsd:element name="metaInfo" minOccurs="0" maxOccurs="1" type="checklistMetaInfo" />
      <xsd:element name="nextChecklistId" minOccurs="1" maxOccurs="1" type="nextChecklistId" />
    </xsd:sequence>
    <xsd:attribute name="id" type="nonemptyString" use="required"/>
    <xsd:attribute name="callSpeech" type="nonemptyString" use="optional"/>
    <xsd:attribute name="sequence" type="xsd:integer" use="optional"/>
    <xsd:attribute name="beginCallFile" type="nonemptyString" use="optional"/>
    <xsd:attribute name="endCallFile" type="nonemptyString" use="optional"/>
  </xsd:complexType>

  <xsd:complexType name="checklistMetaInfo">
    <xsd:sequence>
      <xsd:element name="autostart" minOccurs="0" maxOccurs="1" type="autostartConditionTop" />
      <xsd:element name="customEntrySpeech" minOccurs="0" maxOccurs="1" type="callOrConfirmation" />
      <xsd:element name="customExitSpeech" minOccurs="0" maxOccurs="1" type="callOrConfirmation" />
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="autostartConditionTop">
    <xsd:choice minOccurs="1" maxOccurs="1">
      <xsd:element name="and" type="autostartCondition"/>
      <xsd:element name="or" type="autostartCondition"/>
      <xsd:element name="property" type="autostartProperty"/>
      <xsd:element name="for" type="autostartDelay" />
    </xsd:choice>
  </xsd:complexType>

  <xsd:complexType name="autostartCondition">
    <xsd:choice minOccurs="1" maxOccurs="unbounded">
      <xsd:element name="and" type="autostartCondition"/>
      <xsd:element name="or" type="autostartCondition"/>
      <xsd:element name="property" type="autostartProperty"/>
      <xsd:element name="for" type="autostartDelay" />
    </xsd:choice>
  </xsd:complexType>

  <xsd:complexType name="autostartDelay">
    <xsd:choice minOccurs="1" maxOccurs="1">
      <xsd:element name="and" type="autostartCondition"/>
      <xsd:element name="or" type="autostartCondition"/>
      <xsd:element name="property" type="autostartProperty"/>
    </xsd:choice>
    <xsd:attribute name="seconds" type="xsd:nonNegativeInteger" use="required" />
  </xsd:complexType>

  <xsd:complexType name="autostartProperty">
    <xsd:attribute name="name" type="autostartPropertyName" use="required"/>
    <xsd:attribute name="direction" type="autostartPropertyDirection" use="required" />
    <xsd:attribute name="value" type="xsd:integer" use="required"/>
    <xsd:attribute name="nameIndex" type="xsd:integer" use="optional" />
  </xsd:complexType>

  <xsd:simpleType name="autostartPropertyDirection">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="above"/>
      <xsd:enumeration value="below"/>
    </xsd:restriction>
  </xsd:simpleType>
  
  <xsd:simpleType name="autostartPropertyName">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="altitude"/>
      <xsd:enumeration value="height"/>
      <xsd:enumeration value="gs"/>
      <xsd:enumeration value="ias" />
      <xsd:enumeration value="bank" />
      <xsd:enumeration value="parkingBrakeSet" />
      <xsd:enumeration value="pushbackTugConnected" />
      <xsd:enumeration value="engineStarted" />
      <xsd:enumeration value="verticalSpeed" />
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:simpleType name="autostartPropertyValue">
    <xsd:restriction base="xsd:string">
      <xsd:pattern value="((gt)|(lt))?-?\d+"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:complexType name="nextChecklistId">
    <xsd:attribute name="id" type="nonemptyString" use="optional"/>
  </xsd:complexType>

  <xsd:complexType name="item">
    <xsd:sequence>
      <xsd:element name="call" type="callOrConfirmation"/>
      <xsd:element name="confirmation" type="callOrConfirmation"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="callOrConfirmation">
    <xsd:attribute name="type" type="callOrConfirmationType" use="required"/>
    <xsd:attribute name="value" type="nonemptyString" use="required"/>
  </xsd:complexType>

  <xsd:simpleType name="callOrConfirmationType">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="file"/>
      <xsd:enumeration value="speech"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:simpleType name="nonemptyString">
    <xsd:restriction base="xsd:string">
      <xsd:pattern value=".+"/>
    </xsd:restriction>
  </xsd:simpleType>
</xsd:schema>

=== Engin1980/ChlaotSolution/ChecklistModule/Xmls/cj4.checklist.xml
<?xml version="1.0" encoding="utf-8" ?>
<checklistSet
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns="http://tempuri.org/Schema.xsd"
  xsi:noNamespaceSchemaLocation="ChecklistSchema.xsd"
  xmlns:mt="http://tempuri.org/metaData.xsd"
  xmlns:cs="http://tempuri.org/stateCheck.xsd"
  firstChecklistId="batteryOn">
  <meta>
    <mt:label>CJ4 checklist</mt:label>
    <mt:author>Marek Vajgl</mt:author>
    <mt:description>Simple checklists test for Working Title CJ4</mt:description>
  </meta>
  <checklist id="beforeStart" callSpeech="Before Start-up">
    <item>
      <call type="speech" value="Sim toolkit started"/>
      <confirmation type="speech" value="checked"/>
    </item>
    <item>
      <call type="speech" value="Navigraph started"/>
      <confirmation type="speech" value="checked"/>
    </item>
    <item>
      <call type="speech" value="Battery Switch"/>
      <confirmation type="speech" value="on"/>
    </item>
    <item>
      <call type="speech" value="Emergency Light Switch"/>
      <confirmation type="speech" value="on"/>
    </item>
    <item>
      <call type="speech" value="Standby Flight Display Switch"/>
      <confirmation type="speech" value="on"/>
    </item>
    <item>
      <call type="speech" value="Parking Brake"/>
      <confirmation type="speech" value="Set"/>
    </item>
    <item>
      <call type="speech" value="Passenger Briefing"/>
      <confirmation type="speech" value="Started"/>
    </item>
    <item>
      <call type="speech" value="Seatbelts"/>
      <confirmation type="speech" value="On"/>
    </item>
    <item>
      <call type="speech" value="Climate Control"/>
      <confirmation type="speech" value="Off"/>
    </item>
    <item>
      <call type="speech" value="Beacon Light"/>
      <confirmation type="speech" value="On"/>
    </item>
    <item>
      <call type="speech" value="Throttles"/>
      <confirmation type="speech" value="Idle"/>
    </item>
    <metaInfo>
    </metaInfo>
    <nextChecklistId />
  </checklist>
  <checklist id="beforeTaxi" callSpeech="Before Taxi">
    <item>
      <call type="speech" value="Avionics Switch"/>
      <confirmation type="speech" value="On"/>
    </item>
    <item>
      <call type="speech" value="Climate Control Selector"/>
      <confirmation type="speech" value="On"/>
    </item>
    <item>
      <call type="speech" value="Taxi Lights"/>
      <confirmation type="speech" value="On"/>
    </item>
    <metaInfo>
      <autostart>
        <cs:and>
          <cs:property name="pushbackTugConnected" direction="below" expression="1" />
          <cs:property name="engineStarted" nameIndex="1" direction="above" expression="0"/>
          <cs:property name="engineStarted" nameIndex="2" direction="above" expression="0"/>
          <cs:for seconds="3">
            <cs:property name="parkingBrakeSet" direction="below" expression="1"/>
          </cs:for>
        </cs:and>
      </autostart>
    </metaInfo>
    <nextChecklistId />
  </checklist>
  <checklist id="beforeTakeoff" callSpeech="Before Take Off">
    <item>
      <call type="speech" value="Ice Protection System" />
      <confirmation type="speech" value="Check" />
    </item>
    <item>
      <call type="speech" value="Climate Control Selector" />
      <confirmation type="speech" value="Off" />
    </item>
    <item>
      <call type="speech" value="Pitot Heat" />
      <confirmation type="speech" value="On" />
    </item>
    <item>
      <call type="speech" value="Flaps" />
      <confirmation type="speech" value="Set" />
    </item>
    <item>
      <call type="speech" value="Lights" />
      <confirmation type="speech" value="On" />
    </item>
    <item>
      <call type="speech" value="Squawk Mode" />
      <confirmation type="speech" value="Charlie" />
    </item>
    <item>
      <call type="speech" value="Toga" />
      <confirmation type="speech" value="Set" />
    </item>
    <nextChecklistId/>
  </checklist>
  <checklist id="afterTakeoff" callSpeech="After Take Off">
    <item>
      <call type="speech" value="Gear" />
      <confirmation type="speech" value="Up" />
    </item>
    <metaInfo>
      <autostart>
        <cs:property name="height" direction="above" expression="400"/>
      </autostart>
    </metaInfo>
    <nextChecklistId/>
  </checklist>
  <checklist id="departure" callSpeech="Departure">
    <item>
      <call type="speech" value="Flaps" />
      <confirmation type="speech" value="Up" />
    </item>
    <item>
      <call type="speech" value="Climate Control" />
      <confirmation type="speech" value="On" />
    </item>
    <metaInfo>
      <autostart>
        <cs:and>
          <cs:property name="height" direction="above" expression="1500"/>
          <cs:property name="ias" direction="above" expression="180"/>
        </cs:and>
      </autostart>
    </metaInfo>
    <nextChecklistId/>
  </checklist>
  <checklist id="descend" callSpeech="Descend">
    <item>
      <call type="speech" value="Arrival"/>
      <confirmation type="speech" value="Set"/>
    </item>
    <item>
      <call type="speech" value="Arrival and approach"/>
      <confirmation type="speech" value="Set"/>
    </item>
    <item>
      <call type="speech" value="Decision height" />
      <confirmation type="speech" value="Set" />
    </item>
    <item>
      <call type="speech" value="Reference speeds" />
      <confirmation type="speech" value="Set" />
    </item>
    <metaInfo>
      <autostart>
        <cs:for seconds="60">
          <cs:property name="verticalSpeed" direction="below" expression="-1800"/>
        </cs:for>
      </autostart>
    </metaInfo>
    <nextChecklistId/>
  </checklist>
  <checklist id="approach" callSpeech="Approach">
    <item>
      <call type="speech" value="Flaps" />
      <confirmation type="speech" value="Set" />
    </item>
    <item>
      <call type="speech" value="Lights" />
      <confirmation type="speech" value="On" />
    </item>
    <item>
      <call type="speech" value="Seat Belts" />
      <confirmation type="speech" value="On" />
    </item>
    <metaInfo>
      <autostart>
        <cs:and>
          <cs:property name="ias" direction="below" expression="200"/>
          <cs:property name="height" direction="below" expression="10000"/>
        </cs:and>
      </autostart>
    </metaInfo>
    <nextChecklistId/>
  </checklist>
  <checklist id="shortFinal" callSpeech="Short Final">
    <item>
      <call type="speech" value="Landing Gear" />
      <confirmation type="speech" value="Down Three Green" />
    </item>
    <item>
      <call type="speech" value="Flaps" />
      <confirmation type="speech" value="Full" />
    </item>
    <item>
      <call type="speech" value="Speed brake" />
      <confirmation type="speech" value="None" />
    </item>
    <item>
      <call type="speech" value="Landing Clearance" />
      <confirmation type="speech" value="Obtained" />
    </item>
    <metaInfo>
      <autostart>
        <cs:and>
          <cs:property name="ias" direction="below" expression="200"/>
          <cs:property name="height" direction="below" expression="1000"/>
        </cs:and>
      </autostart>
    </metaInfo>
    <nextChecklistId id="vacated" />
  </checklist>
  <checklist id="goAround" callSpeech="Go Around">
    <item>
      <call type="speech" value="Gear"/>
      <confirmation type="speech" value="Up"/>
    </item>
    <item>
      <call type="speech" value="Flaps"/>
      <confirmation type="speech" value="Checked"/>
    </item>
    <nextChecklistId id="approach" />
  </checklist>
  <checklist id="vacated" callSpeech="Vacated">
    <item>
      <call type="speech" value="Speed Brakes" />
      <confirmation type="speech" value="Retracted" />
    </item>
    <item>
      <call type="speech" value="Flaps" />
      <confirmation type="speech" value="Up" />
    </item>
    <item>
      <call type="speech" value="Squawk" />
      <confirmation type="speech" value="Stand by" />
    </item>
    <item>
      <call type="speech" value="Lights" />
      <confirmation type="speech" value="Off" />
    </item>
    <nextChecklistId id="beforeStart" />
  </checklist>
</checklistSet>

=== Engin1980/ChlaotSolution/Modules/ChecklistModule/Xmls/baron.checklist.xml
<?xml version="1.0" encoding="utf-8" ?>
<checklistSet
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns="http://tempuri.org/chlaotModule.xsd"
  xsi:noNamespaceSchemaLocation="ChecklistSchema.xsd"
  firstChecklistId="batteryOn">
  <meta>
    <label>Baron B58 checklist</label>
    <author>Marek Vajgl</author>
    <description>Simple checklists Baron B58 default plane</description>
  </meta>
  <checklist id="beforeStart" callSpeech="Before Start-up">
    <item>
      <call type="speech" value="Parking Brake"/>
      <confirmation type="speech" value="Set"/>
    </item>
    <item>
      <call type="speech" value="Avionics"/>
      <confirmation type="speech" value="Off"/>
    </item>
    <item>
      <call type="speech" value="Landing Gear"/>
      <confirmation type="speech" value="Down"/>
    </item>
    <item>
      <call type="speech" value="Fuel Selectors"/>
      <confirmation type="speech" value="On"/>
    </item>
    <item>
      <call type="speech" value="Batery Switch"/>
      <confirmation type="speech" value="On"/>
    </item>
    <item>
      <call type="speech" value="Beacon Light"/>
      <confirmation type="speech" value="On"/>
    </item>
    <item>
      <call type="speech" value="Fuel Quantity"/>
      <confirmation type="speech" value="Checked"/>
    </item>
    <metaInfo>
    </metaInfo>
    <nextChecklistId />
  </checklist>
  <checklist id="beforeTaxi" callSpeech="Before Taxi">
    <item>
      <call type="speech" value="Alternator Switch"/>
      <confirmation type="speech" value="On"/>
    </item>
    <item>
      <call type="speech" value="Voltmeter"/>
      <confirmation type="speech" value="28 volts at least"/>
    </item>
    <item>
      <call type="speech" value="Avionics"/>
      <confirmation type="speech" value="On"/>
    </item>
    <item>
      <call type="speech" value="Exterior Lights"/>
      <confirmation type="speech" value="On"/>
    </item>
    <item>
      <call type="speech" value="Surfaces"/>
      <confirmation type="speech" value="Checked"/>
    </item>
    <item>
      <call type="speech" value="Trim"/>
      <confirmation type="speech" value="Set"/>
    </item>
    <item>
      <call type="speech" value="Flaps"/>
      <confirmation type="speech" value="Set"/>
    </item>
    <metaInfo>
      <when>
        <and>
          <property name="pushbackTugConnected" direction="below" expression="1" />
          <property name="engineStarted" nameIndex="1" direction="above" expression="0"/>
          <property name="engineStarted" nameIndex="2" direction="above" expression="0"/>
          <for seconds="3">
            <property name="parkingBrakeSet" direction="below" expression="1"/>
          </for>
        </and>
      </when>
    </metaInfo>
    <nextChecklistId />
  </checklist>
  <checklist id="beforeTakeoff" callSpeech="Before Take Off">
    <item>
      <call type="speech" value="Seat Belts"/>
      <confirmation type="speech" value="On"/>
    </item>
    <item>
      <call type="speech" value="Mixture"/>
      <confirmation type="speech" value="Set"/>
    </item>
    <item>
      <call type="speech" value="Propeller"/>
      <confirmation type="speech" value="Feathering"/>
    </item>
    <item>
      <call type="speech" value="Landing Lights"/>
      <confirmation type="speech" value="On"/>
    </item>
    <item>
      <call type="speech" value="Strobe Light"/>
      <confirmation type="speech" value="On"/>
    </item>
    <item>
      <call type="speech" value="Transponder mode"/>
      <confirmation type="speech" value="Charlie"/>
    </item>
    <nextChecklistId/>
  </checklist>
  <checklist id="afterTakeoff" callSpeech="After Take Off">
    <item>
      <call type="speech" value="Gear" />
      <confirmation type="speech" value="Up" />
    </item>
    <item>
      <call type="speech" value="Landing Lights" />
      <confirmation type="speech" value="Off" />
    </item>
    <metaInfo>
      <when>
        <property name="height" direction="above" expression="400"/>
      </when>
    </metaInfo>
    <nextChecklistId/>
  </checklist>
  <checklist id="departure" callSpeech="Departure">
    <item>
      <call type="speech" value="Flaps" />
      <confirmation type="speech" value="Up" />
    </item>
    <item>
      <call type="speech" value="Fuel Boost Pump" />
      <confirmation type="speech" value="Off" />
    </item>
    <item>
      <call type="speech" value="Cowl Flaps" />
      <confirmation type="speech" value="Closed" />
    </item>
    <metaInfo>
      <when>
        <and>
          <property name="height" direction="above" expression="1500"/>
          <property name="ias" direction="above" expression="180"/>
        </and>
      </when>
    </metaInfo>
    <nextChecklistId/>
  </checklist>
  <checklist id="descend" callSpeech="Descend">
    <item>
      <call type="speech" value="Altimeter"/>
      <confirmation type="speech" value="Set"/>
    </item>
    <item>
      <call type="speech" value="Mixture"/>
      <confirmation type="speech" value="Set full"/>
    </item>
    <item>
      <call type="speech" value="Cowl flaps" />
      <confirmation type="speech" value="Closed" />
    </item>
    <item>
      <call type="speech" value="Reference speeds" />
      <confirmation type="speech" value="Set" />
    </item>
    <metaInfo>
      <when>
        <for seconds="60">
          <property name="verticalSpeed" direction="below" expression="-1800"/>
        </for>
      </when>
    </metaInfo>
    <nextChecklistId/>
  </checklist>
  <checklist id="approach" callSpeech="Approach">
    <item>
      <call type="speech" value="Flaps" />
      <confirmation type="speech" value="Set" />
    </item>
    <item>
      <call type="speech" value="Lights" />
      <confirmation type="speech" value="On" />
    </item>
    <item>
      <call type="speech" value="Seat Belts" />
      <confirmation type="speech" value="On" />
    </item>
    <metaInfo>
      <when>
        <and>
          <property name="ias" direction="below" expression="200"/>
          <property name="height" direction="below" expression="10000"/>
        </and>
      </when>
    </metaInfo>
    <nextChecklistId/>
  </checklist>
  <checklist id="shortFinal" callSpeech="Short Final">
    <item>
      <call type="speech" value="Landing Gear" />
      <confirmation type="speech" value="Down Three Green" />
    </item>
    <item>
      <call type="speech" value="Flaps" />
      <confirmation type="speech" value="Full" />
    </item>
    <item>
      <call type="speech" value="Speed brake" />
      <confirmation type="speech" value="None" />
    </item>
    <item>
      <call type="speech" value="Landing Clearance" />
      <confirmation type="speech" value="Obtained" />
    </item>
    <metaInfo>
      <when>
        <and>
          <property name="ias" direction="below" expression="200"/>
          <property name="height" direction="below" expression="1000"/>
        </and>
      </when>
    </metaInfo>
    <nextChecklistId id="vacated" />
  </checklist>
  <checklist id="goAround" callSpeech="Go Around">
    <item>
      <call type="speech" value="Gear"/>
      <confirmation type="speech" value="Up"/>
    </item>
    <item>
      <call type="speech" value="Flaps"/>
      <confirmation type="speech" value="Checked"/>
    </item>
    <nextChecklistId id="approach" />
  </checklist>
  <checklist id="vacated" callSpeech="Vacated">
    <item>
      <call type="speech" value="Speed Brakes" />
      <confirmation type="speech" value="Retracted" />
    </item>
    <item>
      <call type="speech" value="Flaps" />
      <confirmation type="speech" value="Up" />
    </item>
    <item>
      <call type="speech" value="Squawk" />
      <confirmation type="speech" value="Stand by" />
    </item>
    <item>
      <call type="speech" value="Lights" />
      <confirmation type="speech" value="Off" />
    </item>
    <nextChecklistId id="beforeStart" />
  </checklist>
</checklistSet>

=== Engin1980/ChlaotSolution/ChecklistModule/Xmls/cj4.xml
<?xml version="1.0" encoding="utf-8" ?>
<checklistSet
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns="http://tempuri.org/Schema.xsd"
  xsi:noNamespaceSchemaLocation="ChecklistSchema.xsd"
  firstChecklistId="batteryOn">
  <meta>
    <label>CJ4 checklist</label>
    <author>Marek Vajgl</author>
    <description>Simple checklists test for Working Title CJ4</description>
  </meta>
  <checklist id="beforeStart" callSpeech="Before Start-up">
    <item>
      <call type="speech" value="Battery Switch"/>
      <confirmation type="speech" value="on"/>
    </item>
    <item>
      <call type="speech" value="Emergency Light Switch"/>
      <confirmation type="speech" value="on"/>
    </item>
    <item>
      <call type="speech" value="Standby Flight Display Switch"/>
      <confirmation type="speech" value="on"/>
    </item>
    <item>
      <call type="speech" value="Avionics Switch"/>
      <confirmation type="speech" value="Dispatch"/>
    </item>
    <item>
      <call type="speech" value="Parking Brake"/>
      <confirmation type="speech" value="Set"/>
    </item>
    <item>
      <call type="speech" value="Passenger Briefing"/>
      <confirmation type="speech" value="Started"/>
    </item>
    <item>
      <call type="speech" value="Seatbelts"/>
      <confirmation type="speech" value="On"/>
    </item>
    <item>
      <call type="speech" value="Climate Control"/>
      <confirmation type="speech" value="Off"/>
    </item>
    <metaInfo>
      <autostart>
        <and>
          <or>
            <property name="ias" direction="above" value="30" />
            <for seconds="10">
              <property name="height" direction="above" value="0" />
            </for>
          </or>
        </and>
      </autostart>
      <customEntrySpeech type="speech" value="dudla entry blabla"/>
      <customExitSpeech type="speech" value="bubla exit dada"/>
    </metaInfo>
    <nextChecklistId />
  </checklist>
  <checklist id="start" callSpeech="Start">
    <item>
      <call type="speech" value="Throttles"/>
      <confirmation type="speech" value="Idle"/>
    </item>
    <nextChecklistId />
  </checklist>
  <checklist id="beforeTaxi" callSpeech="Before Taxi">
    <item>
      <call type="speech" value="Avionics Switch"/>
      <confirmation type="speech" value="On"/>
    </item>
    <item>
      <call type="speech" value="Climate Control Selector"/>
      <confirmation type="speech" value="On"/>
    </item>
    <item>
      <call type="speech" value="Taxi Lights"/>
      <confirmation type="speech" value="On"/>
    </item>
    <nextChecklistId />
  </checklist>
  <checklist id="inTaxi" callSpeech="In Taxi" beginCallFile="sound/inTaxiStart.wav" endCallFile="sound/inTaxiCompleted.wav">
    <item>
      <call type="speech" value="sound/cj4/flaps.wav"/>
      <confirmation type="speech" value="sound/set.wav"/>
    </item>
  </checklist>
  <checklist id="beforeTakeoff" callSpeech="Before Take Off">
    <item>
      <call type="speech" value="Ice Protection System" />
      <confirmation type="speech" value="Check" />
    </item>
    <nextChecklistId/>
  </checklist>
  <checklist id="takeoff" callSpeech="Take Off">
    <item>
      <call type="speech" value="Throttles" />
      <confirmation type="speech" value="Take Off" />
    </item>
    <nextChecklistId/>
  </checklist>
  <checklist id="afterTakeoff" callSpeech="After Take Off">
    <item>
      <call type="speech" value="Landing Gear" />
      <confirmation type="speech" value="Up" />
    </item>
    <nextChecklistId/>
  </checklist>
  <checklist id="descent" callSpeech="Descent">
    <item>
      <call type="speech" value="Pressurezation" />
      <confirmation type="speech" value="Verify" />
    </item>
    <nextChecklistId/>
  </checklist>
  <checklist id="approach" callSpeech="Approach">
    <item>
      <call type="speech" value="Landing Data" />
      <confirmation type="speech" value="Check" />
    </item>
    <nextChecklistId/>
  </checklist>
  <checklist id="beforeLanding" callSpeech="Before Landing">
    <item>
      <call type="speech" value="Landing Gear" />
      <confirmation type="speech" value="Down Three Green" />
    </item>
    <nextChecklistId id="vacated" />
    <checklist id="goAround" callSpeech="Go Around">
      <item>
        <call type="speech" value="Gear"/>
        <confirmation type="speech" value="Up"/>
      </item>
      <item>
        <call type="speech" value="Flaps"/>
        <confirmation type="speech" value="As required"/>
      </item>
      <nextChecklistId id="approach" />
    </checklist>
  </checklist>
  <checklist id="vacated" callSpeech="Vacated">
    <item>
      <call type="speech" value="Speed Brakes" />
      <confirmation type="speech" value="Retracted" />
    </item>
    <nextChecklistId id="beforeStart" />
  </checklist>
</checklistSet>
